x = input('Digite algo\n')
print('O pito primitivo é', type(x))
print('É númerico?', x.isnumeric())
print('É alfabético?', x.isalpha())
print('É alfanumérico?', x.isalnum())
print('Está em maiuscula?', x.isupper())
print('Éstá em minuscula?', x.islower())
print('Está capitalizada?', x.istitle())
print('É somente espaço?', x.isspace())